name: Continuous Deployment - FastAPI to Vercel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7   
      - name: List files in the repository  
        run: |
          ls -alp
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
